{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE RecordWildCards #-}
{-# LANGUAGE PartialTypeSignatures #-}

module Main where

import Data.Typeable (Proxy(..))
import Test.Hspec
import Test.Hspec.QuickCheck

import PropMime
import Instances ()

import TransportForLondonUnified.Model
import TransportForLondonUnified.MimeTypes

main :: IO ()
main =
  hspec $ modifyMaxSize (const 5) $ do
    describe "JSON instances" $ do
      pure ()
      propMimeEq MimeJSON (Proxy :: Proxy SystemDataSpatialDbGeography)
      propMimeEq MimeJSON (Proxy :: Proxy SystemDataSpatialDbGeographyWellKnownValue)
      propMimeEq MimeJSON (Proxy :: Proxy SystemObject)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiCommonApiVersionInfo)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiCommonDateRange)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiCommonDateRangeNullable)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiCommonGeoPoint)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiCommonJourneyPlannerJpElevation)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiCommonPlaceGeo)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiCommonPostcodeInput)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesAccidentStatsAccidentDetail)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesAccidentStatsAccidentStatsOrderedSummary)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesAccidentStatsCasualty)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesAccidentStatsVehicle)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesActiveServiceType)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesAdditionalProperties)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesArrivalDeparture)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesArrivalDepartureWithLine)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesBay)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesBikePointOccupancy)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesCarParkOccupancy)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesChargeConnectorOccupancy)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesCoordinate)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesCrowding)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesCycleSuperhighway)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesDisruptedPoint)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesDisruptedRoute)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesDisruption)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesFaresFare)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesFaresFareBounds)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesFaresFareDetails)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesFaresFareStation)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesFaresFaresMode)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesFaresFaresPeriod)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesFaresFaresSection)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesFaresJourney)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesFaresPassengerType)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesFaresRecommendation)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesFaresRecommendationResponse)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesFaresTicket)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesFaresTicketTime)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesFaresTicketType)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesGeoCodeSearchMatch)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesIdentifier)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesInstruction)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesInstructionStep)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesInterval)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesJourneyPlannerFare)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesJourneyPlannerFareCaveat)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesJourneyPlannerFareTap)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesJourneyPlannerFareTapDetails)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesJourneyPlannerItineraryResult)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesJourneyPlannerJourney)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesJourneyPlannerJourneyFare)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesJourneyPlannerJourneyPlannerCycleHireDockingStationData)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesJourneyPlannerJourneyVector)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesJourneyPlannerLeg)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesJourneyPlannerObstacle)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesJourneyPlannerPath)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesJourneyPlannerPlannedWork)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesJourneyPlannerRouteOption)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesJourneyPlannerSearchCriteria)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesJourneyPlannerTimeAdjustment)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesJourneyPlannerTimeAdjustments)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesKnownJourney)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesLine)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesLineGroup)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesLineModeGroup)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesLineRouteSection)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesLineServiceType)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesLineServiceTypeInfo)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesLineSpecificServiceType)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesLineStatus)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesMatchedRoute)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesMatchedRouteSections)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesMatchedStop)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesMessage)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesMode)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesNetworkStatus)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesOrderedRoute)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesPassengerFlow)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesPathAttribute)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesPeriod)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesPlace)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesPlaceCategory)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesPlacePolygon)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesPoint)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesPrediction)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesPredictionTiming)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesRedirect)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesRoadCorridor)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesRoadDisruption)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesRoadDisruptionImpactArea)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesRoadDisruptionLine)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesRoadDisruptionSchedule)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesRoadProject)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesRouteSearchMatch)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesRouteSearchResponse)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesRouteSectionNaptanEntrySequence)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesRouteSequence)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesSchedule)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesSearchMatch)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesSearchResponse)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesServiceFrequency)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesStationInterval)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesStatusSeverity)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesStopPoint)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesStopPointCategory)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesStopPointRouteSection)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesStopPointSequence)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesStopPointsResponse)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesStreet)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesStreetSegment)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesTimetable)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesTimetableResponse)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesTimetableRoute)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesTimetablesDisambiguation)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesTimetablesDisambiguationOption)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesTrainLoading)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesTwentyFourHourClockTime)
      propMimeEq MimeJSON (Proxy :: Proxy TflApiPresentationEntitiesValidityPeriod)
      
