{-
   Transport for London Unified API

   No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

   OpenAPI spec version: 2.0
   Transport for London Unified API API version: v1
   Generated by Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
-}

{-|
Module : TransportForLondonUnified.API.AccidentStats
-}

{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE MonoLocalBinds #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing -fno-warn-unused-binds -fno-warn-unused-imports #-}

module TransportForLondonUnified.API.AccidentStats where

import TransportForLondonUnified.Core
import TransportForLondonUnified.MimeTypes
import TransportForLondonUnified.Model as M

import qualified Data.Aeson as A
import qualified Data.ByteString as B
import qualified Data.ByteString.Lazy as BL
import qualified Data.Data as P (Typeable, TypeRep, typeOf, typeRep)
import qualified Data.Foldable as P
import qualified Data.Map as Map
import qualified Data.Maybe as P
import qualified Data.Proxy as P (Proxy(..))
import qualified Data.Set as Set
import qualified Data.String as P
import qualified Data.Text as T
import qualified Data.Text.Encoding as T
import qualified Data.Text.Lazy as TL
import qualified Data.Text.Lazy.Encoding as TL
import qualified Data.Time as TI
import qualified Network.HTTP.Client.MultipartFormData as NH
import qualified Network.HTTP.Media as ME
import qualified Network.HTTP.Types as NH
import qualified Web.FormUrlEncoded as WH
import qualified Web.HttpApiData as WH

import Data.Text (Text)
import GHC.Base ((<|>))

import Prelude ((==),(/=),($), (.),(<$>),(<*>),(>>=),Maybe(..),Bool(..),Char,Double,FilePath,Float,Int,Integer,String,fmap,undefined,mempty,maybe,pure,Monad,Applicative,Functor)
import qualified Prelude as P

-- * Operations


-- ** AccidentStats

-- *** accidentStatsGet

-- | @GET \/AccidentStats\/{year}@
-- 
-- Gets all accident details for accidents occuring in the specified year
-- 
accidentStatsGet 
  :: Accept accept -- ^ request accept ('MimeType')
  -> Year -- ^ "year" -  The year for which to filter the accidents on.
  -> TransportForLondonUnifiedRequest AccidentStatsGet MimeNoContent [TflApiPresentationEntitiesAccidentStatsAccidentDetail] accept
accidentStatsGet  _ (Year year) =
  _mkRequest "GET" ["/AccidentStats/",toPath year]

data AccidentStatsGet  
-- | @application/json@
instance Produces AccidentStatsGet MimeJSON
-- | @text/json@
instance Produces AccidentStatsGet MimeTextjson
-- | @application/xml@
instance Produces AccidentStatsGet MimeXML
-- | @text/xml@
instance Produces AccidentStatsGet MimeTextxml

