{-
   Transport for London Unified API

   No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

   OpenAPI spec version: 2.0
   Transport for London Unified API API version: v1
   Generated by Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
-}

{-|
Module : TransportForLondonUnified.API.Cabwise
-}

{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE MonoLocalBinds #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing -fno-warn-unused-binds -fno-warn-unused-imports #-}

module TransportForLondonUnified.API.Cabwise where

import TransportForLondonUnified.Core
import TransportForLondonUnified.MimeTypes
import TransportForLondonUnified.Model as M

import qualified Data.Aeson as A
import qualified Data.ByteString as B
import qualified Data.ByteString.Lazy as BL
import qualified Data.Data as P (Typeable, TypeRep, typeOf, typeRep)
import qualified Data.Foldable as P
import qualified Data.Map as Map
import qualified Data.Maybe as P
import qualified Data.Proxy as P (Proxy(..))
import qualified Data.Set as Set
import qualified Data.String as P
import qualified Data.Text as T
import qualified Data.Text.Encoding as T
import qualified Data.Text.Lazy as TL
import qualified Data.Text.Lazy.Encoding as TL
import qualified Data.Time as TI
import qualified Network.HTTP.Client.MultipartFormData as NH
import qualified Network.HTTP.Media as ME
import qualified Network.HTTP.Types as NH
import qualified Web.FormUrlEncoded as WH
import qualified Web.HttpApiData as WH

import Data.Text (Text)
import GHC.Base ((<|>))

import Prelude ((==),(/=),($), (.),(<$>),(<*>),(>>=),Maybe(..),Bool(..),Char,Double,FilePath,Float,Int,Integer,String,fmap,undefined,mempty,maybe,pure,Monad,Applicative,Functor)
import qualified Prelude as P

-- * Operations


-- ** Cabwise

-- *** cabwiseGet

-- | @GET \/Cabwise\/search@
-- 
-- Gets taxis and minicabs contact information
-- 
cabwiseGet 
  :: Accept accept -- ^ request accept ('MimeType')
  -> Lat -- ^ "lat" -  Latitude
  -> Lon -- ^ "lon" -  Longitude
  -> TransportForLondonUnifiedRequest CabwiseGet MimeNoContent SystemObject accept
cabwiseGet  _ (Lat lat) (Lon lon) =
  _mkRequest "GET" ["/Cabwise/search"]
    `setQuery` toQuery ("lat", Just lat)
    `setQuery` toQuery ("lon", Just lon)

data CabwiseGet  

-- | /Optional Param/ "optype" - Operator Type e.g Minicab, Executive, Limousine
instance HasOptionalParam CabwiseGet Optype where
  applyOptionalParam req (Optype xs) =
    req `setQuery` toQuery ("optype", Just xs)

-- | /Optional Param/ "wc" - Wheelchair accessible
instance HasOptionalParam CabwiseGet Wc where
  applyOptionalParam req (Wc xs) =
    req `setQuery` toQuery ("wc", Just xs)

-- | /Optional Param/ "radius" - The radius of the bounding circle in metres
instance HasOptionalParam CabwiseGet Radius where
  applyOptionalParam req (Radius xs) =
    req `setQuery` toQuery ("radius", Just xs)

-- | /Optional Param/ "name" - Trading name of operating company
instance HasOptionalParam CabwiseGet Name where
  applyOptionalParam req (Name xs) =
    req `setQuery` toQuery ("name", Just xs)

-- | /Optional Param/ "maxResults" - An optional parameter to limit the number of results return. Default and maximum is 20.
instance HasOptionalParam CabwiseGet MaxResults where
  applyOptionalParam req (MaxResults xs) =
    req `setQuery` toQuery ("maxResults", Just xs)

-- | /Optional Param/ "legacyFormat" - Legacy Format
instance HasOptionalParam CabwiseGet LegacyFormat where
  applyOptionalParam req (LegacyFormat xs) =
    req `setQuery` toQuery ("legacyFormat", Just xs)

-- | /Optional Param/ "forceXml" - Force Xml
instance HasOptionalParam CabwiseGet ForceXml where
  applyOptionalParam req (ForceXml xs) =
    req `setQuery` toQuery ("forceXml", Just xs)

-- | /Optional Param/ "twentyFourSevenOnly" - Twenty Four Seven Only
instance HasOptionalParam CabwiseGet TwentyFourSevenOnly where
  applyOptionalParam req (TwentyFourSevenOnly xs) =
    req `setQuery` toQuery ("twentyFourSevenOnly", Just xs)
-- | @application/json@
instance Produces CabwiseGet MimeJSON
-- | @text/json@
instance Produces CabwiseGet MimeTextjson
-- | @application/xml@
instance Produces CabwiseGet MimeXML
-- | @text/xml@
instance Produces CabwiseGet MimeTextxml

