{-
   Transport for London Unified API

   No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

   OpenAPI spec version: 2.0
   Transport for London Unified API API version: v1
   Generated by Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
-}

{-|
Module : TransportForLondonUnified.API.Mode
-}

{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE MonoLocalBinds #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing -fno-warn-unused-binds -fno-warn-unused-imports #-}

module TransportForLondonUnified.API.Mode where

import TransportForLondonUnified.Core
import TransportForLondonUnified.MimeTypes
import TransportForLondonUnified.Model as M

import qualified Data.Aeson as A
import qualified Data.ByteString as B
import qualified Data.ByteString.Lazy as BL
import qualified Data.Data as P (Typeable, TypeRep, typeOf, typeRep)
import qualified Data.Foldable as P
import qualified Data.Map as Map
import qualified Data.Maybe as P
import qualified Data.Proxy as P (Proxy(..))
import qualified Data.Set as Set
import qualified Data.String as P
import qualified Data.Text as T
import qualified Data.Text.Encoding as T
import qualified Data.Text.Lazy as TL
import qualified Data.Text.Lazy.Encoding as TL
import qualified Data.Time as TI
import qualified Network.HTTP.Client.MultipartFormData as NH
import qualified Network.HTTP.Media as ME
import qualified Network.HTTP.Types as NH
import qualified Web.FormUrlEncoded as WH
import qualified Web.HttpApiData as WH

import Data.Text (Text)
import GHC.Base ((<|>))

import Prelude ((==),(/=),($), (.),(<$>),(<*>),(>>=),Maybe(..),Bool(..),Char,Double,FilePath,Float,Int,Integer,String,fmap,undefined,mempty,maybe,pure,Monad,Applicative,Functor)
import qualified Prelude as P

-- * Operations


-- ** Mode

-- *** modeArrivals

-- | @GET \/Mode\/{mode}\/Arrivals@
-- 
-- Gets the next arrival predictions for all stops of a given mode
-- 
modeArrivals 
  :: Accept accept -- ^ request accept ('MimeType')
  -> ModeText -- ^ "mode" -  A mode name e.g. tube, dlr
  -> TransportForLondonUnifiedRequest ModeArrivals MimeNoContent [TflApiPresentationEntitiesPrediction] accept
modeArrivals  _ (ModeText mode) =
  _mkRequest "GET" ["/Mode/",toPath mode,"/Arrivals"]

data ModeArrivals  

-- | /Optional Param/ "count" - A number of arrivals to return for each stop, -1 to return all available.
instance HasOptionalParam ModeArrivals Count where
  applyOptionalParam req (Count xs) =
    req `setQuery` toQuery ("count", Just xs)
-- | @application/json@
instance Produces ModeArrivals MimeJSON
-- | @text/json@
instance Produces ModeArrivals MimeTextjson
-- | @application/xml@
instance Produces ModeArrivals MimeXML
-- | @text/xml@
instance Produces ModeArrivals MimeTextxml


-- *** modeGetActiveServiceTypes

-- | @GET \/Mode\/ActiveServiceTypes@
-- 
-- Returns the service type active for a mode.              Currently only supports tube
-- 
modeGetActiveServiceTypes 
  :: Accept accept -- ^ request accept ('MimeType')
  -> TransportForLondonUnifiedRequest ModeGetActiveServiceTypes MimeNoContent [TflApiPresentationEntitiesActiveServiceType] accept
modeGetActiveServiceTypes  _ =
  _mkRequest "GET" ["/Mode/ActiveServiceTypes"]

data ModeGetActiveServiceTypes  
-- | @application/json@
instance Produces ModeGetActiveServiceTypes MimeJSON
-- | @text/json@
instance Produces ModeGetActiveServiceTypes MimeTextjson
-- | @application/xml@
instance Produces ModeGetActiveServiceTypes MimeXML
-- | @text/xml@
instance Produces ModeGetActiveServiceTypes MimeTextxml

