{-
   Transport for London Unified API

   No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

   OpenAPI spec version: 2.0
   Transport for London Unified API API version: v1
   Generated by Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
-}

{-|
Module : TransportForLondonUnified.API.Occupancy
-}

{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE MonoLocalBinds #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing -fno-warn-unused-binds -fno-warn-unused-imports #-}

module TransportForLondonUnified.API.Occupancy where

import TransportForLondonUnified.Core
import TransportForLondonUnified.MimeTypes
import TransportForLondonUnified.Model as M

import qualified Data.Aeson as A
import qualified Data.ByteString as B
import qualified Data.ByteString.Lazy as BL
import qualified Data.Data as P (Typeable, TypeRep, typeOf, typeRep)
import qualified Data.Foldable as P
import qualified Data.Map as Map
import qualified Data.Maybe as P
import qualified Data.Proxy as P (Proxy(..))
import qualified Data.Set as Set
import qualified Data.String as P
import qualified Data.Text as T
import qualified Data.Text.Encoding as T
import qualified Data.Text.Lazy as TL
import qualified Data.Text.Lazy.Encoding as TL
import qualified Data.Time as TI
import qualified Network.HTTP.Client.MultipartFormData as NH
import qualified Network.HTTP.Media as ME
import qualified Network.HTTP.Types as NH
import qualified Web.FormUrlEncoded as WH
import qualified Web.HttpApiData as WH

import Data.Text (Text)
import GHC.Base ((<|>))

import Prelude ((==),(/=),($), (.),(<$>),(<*>),(>>=),Maybe(..),Bool(..),Char,Double,FilePath,Float,Int,Integer,String,fmap,undefined,mempty,maybe,pure,Monad,Applicative,Functor)
import qualified Prelude as P

-- * Operations


-- ** Occupancy

-- *** occupancyGet

-- | @GET \/Occupancy\/CarPark\/{id}@
-- 
-- Gets the occupancy for a car park with a given id
-- 
occupancyGet 
  :: Accept accept -- ^ request accept ('MimeType')
  -> Id -- ^ "id" -  
  -> TransportForLondonUnifiedRequest OccupancyGet MimeNoContent TflApiPresentationEntitiesCarParkOccupancy accept
occupancyGet  _ (Id id) =
  _mkRequest "GET" ["/Occupancy/CarPark/",toPath id]

data OccupancyGet  
-- | @application/json@
instance Produces OccupancyGet MimeJSON
-- | @text/json@
instance Produces OccupancyGet MimeTextjson
-- | @application/xml@
instance Produces OccupancyGet MimeXML
-- | @text/xml@
instance Produces OccupancyGet MimeTextxml


-- *** occupancyGet0

-- | @GET \/Occupancy\/CarPark@
-- 
-- Gets the occupancy for all car parks that have occupancy data
-- 
occupancyGet0 
  :: Accept accept -- ^ request accept ('MimeType')
  -> TransportForLondonUnifiedRequest OccupancyGet0 MimeNoContent [TflApiPresentationEntitiesCarParkOccupancy] accept
occupancyGet0  _ =
  _mkRequest "GET" ["/Occupancy/CarPark"]

data OccupancyGet0  
-- | @application/json@
instance Produces OccupancyGet0 MimeJSON
-- | @text/json@
instance Produces OccupancyGet0 MimeTextjson
-- | @application/xml@
instance Produces OccupancyGet0 MimeXML
-- | @text/xml@
instance Produces OccupancyGet0 MimeTextxml


-- *** occupancyGetAllChargeConnectorStatus

-- | @GET \/Occupancy\/ChargeConnector@
-- 
-- Gets the occupancy for all charge connectors
-- 
occupancyGetAllChargeConnectorStatus 
  :: Accept accept -- ^ request accept ('MimeType')
  -> TransportForLondonUnifiedRequest OccupancyGetAllChargeConnectorStatus MimeNoContent [TflApiPresentationEntitiesChargeConnectorOccupancy] accept
occupancyGetAllChargeConnectorStatus  _ =
  _mkRequest "GET" ["/Occupancy/ChargeConnector"]

data OccupancyGetAllChargeConnectorStatus  
-- | @application/json@
instance Produces OccupancyGetAllChargeConnectorStatus MimeJSON
-- | @text/json@
instance Produces OccupancyGetAllChargeConnectorStatus MimeTextjson
-- | @application/xml@
instance Produces OccupancyGetAllChargeConnectorStatus MimeXML
-- | @text/xml@
instance Produces OccupancyGetAllChargeConnectorStatus MimeTextxml


-- *** occupancyGetBikePointsOccupancies

-- | @GET \/Occupancy\/BikePoints\/{ids}@
-- 
-- Get the occupancy for bike points.
-- 
occupancyGetBikePointsOccupancies 
  :: Accept accept -- ^ request accept ('MimeType')
  -> Ids -- ^ "ids" -  
  -> TransportForLondonUnifiedRequest OccupancyGetBikePointsOccupancies MimeNoContent [TflApiPresentationEntitiesBikePointOccupancy] accept
occupancyGetBikePointsOccupancies  _ (Ids ids) =
  _mkRequest "GET" ["/Occupancy/BikePoints/",toPath ids]

data OccupancyGetBikePointsOccupancies  
-- | @application/json@
instance Produces OccupancyGetBikePointsOccupancies MimeJSON
-- | @text/json@
instance Produces OccupancyGetBikePointsOccupancies MimeTextjson
-- | @application/xml@
instance Produces OccupancyGetBikePointsOccupancies MimeXML
-- | @text/xml@
instance Produces OccupancyGetBikePointsOccupancies MimeTextxml


-- *** occupancyGetChargeConnectorStatus

-- | @GET \/Occupancy\/ChargeConnector\/{ids}@
-- 
-- Gets the occupancy for a charge connectors with a given id (sourceSystemPlaceId)
-- 
occupancyGetChargeConnectorStatus 
  :: Accept accept -- ^ request accept ('MimeType')
  -> Ids -- ^ "ids"
  -> TransportForLondonUnifiedRequest OccupancyGetChargeConnectorStatus MimeNoContent [TflApiPresentationEntitiesChargeConnectorOccupancy] accept
occupancyGetChargeConnectorStatus  _ (Ids ids) =
  _mkRequest "GET" ["/Occupancy/ChargeConnector/",toPath ids]

data OccupancyGetChargeConnectorStatus  
-- | @application/json@
instance Produces OccupancyGetChargeConnectorStatus MimeJSON
-- | @text/json@
instance Produces OccupancyGetChargeConnectorStatus MimeTextjson
-- | @application/xml@
instance Produces OccupancyGetChargeConnectorStatus MimeXML
-- | @text/xml@
instance Produces OccupancyGetChargeConnectorStatus MimeTextxml

