{-
   Transport for London Unified API

   No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

   OpenAPI spec version: 2.0
   Transport for London Unified API API version: v1
   Generated by Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
-}

{-|
Module : TransportForLondonUnified.API.Search
-}

{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE MonoLocalBinds #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing -fno-warn-unused-binds -fno-warn-unused-imports #-}

module TransportForLondonUnified.API.Search where

import TransportForLondonUnified.Core
import TransportForLondonUnified.MimeTypes
import TransportForLondonUnified.Model as M

import qualified Data.Aeson as A
import qualified Data.ByteString as B
import qualified Data.ByteString.Lazy as BL
import qualified Data.Data as P (Typeable, TypeRep, typeOf, typeRep)
import qualified Data.Foldable as P
import qualified Data.Map as Map
import qualified Data.Maybe as P
import qualified Data.Proxy as P (Proxy(..))
import qualified Data.Set as Set
import qualified Data.String as P
import qualified Data.Text as T
import qualified Data.Text.Encoding as T
import qualified Data.Text.Lazy as TL
import qualified Data.Text.Lazy.Encoding as TL
import qualified Data.Time as TI
import qualified Network.HTTP.Client.MultipartFormData as NH
import qualified Network.HTTP.Media as ME
import qualified Network.HTTP.Types as NH
import qualified Web.FormUrlEncoded as WH
import qualified Web.HttpApiData as WH

import Data.Text (Text)
import GHC.Base ((<|>))

import Prelude ((==),(/=),($), (.),(<$>),(<*>),(>>=),Maybe(..),Bool(..),Char,Double,FilePath,Float,Int,Integer,String,fmap,undefined,mempty,maybe,pure,Monad,Applicative,Functor)
import qualified Prelude as P

-- * Operations


-- ** Search

-- *** searchBusSchedules

-- | @GET \/Search\/BusSchedules@
-- 
-- Searches the bus schedules folder on S3 for a given bus number.
-- 
searchBusSchedules 
  :: Accept accept -- ^ request accept ('MimeType')
  -> Query -- ^ "query" -  The search query
  -> TransportForLondonUnifiedRequest SearchBusSchedules MimeNoContent TflApiPresentationEntitiesSearchResponse accept
searchBusSchedules  _ (Query query) =
  _mkRequest "GET" ["/Search/BusSchedules"]
    `setQuery` toQuery ("query", Just query)

data SearchBusSchedules  
-- | @application/json@
instance Produces SearchBusSchedules MimeJSON
-- | @text/json@
instance Produces SearchBusSchedules MimeTextjson
-- | @application/xml@
instance Produces SearchBusSchedules MimeXML
-- | @text/xml@
instance Produces SearchBusSchedules MimeTextxml


-- *** searchGet

-- | @GET \/Search@
-- 
-- Search the site for occurrences of the query string. The maximum number of results returned is equal to the maximum page size              of 100. To return subsequent pages, use the paginated overload.
-- 
searchGet 
  :: Accept accept -- ^ request accept ('MimeType')
  -> Query -- ^ "query" -  The search query
  -> TransportForLondonUnifiedRequest SearchGet MimeNoContent TflApiPresentationEntitiesSearchResponse accept
searchGet  _ (Query query) =
  _mkRequest "GET" ["/Search"]
    `setQuery` toQuery ("query", Just query)

data SearchGet  
-- | @application/json@
instance Produces SearchGet MimeJSON
-- | @text/json@
instance Produces SearchGet MimeTextjson
-- | @application/xml@
instance Produces SearchGet MimeXML
-- | @text/xml@
instance Produces SearchGet MimeTextxml


-- *** searchMetaCategories

-- | @GET \/Search\/Meta\/Categories@
-- 
-- Gets the available search categories.
-- 
searchMetaCategories 
  :: Accept accept -- ^ request accept ('MimeType')
  -> TransportForLondonUnifiedRequest SearchMetaCategories MimeNoContent [Text] accept
searchMetaCategories  _ =
  _mkRequest "GET" ["/Search/Meta/Categories"]

data SearchMetaCategories  
-- | @application/json@
instance Produces SearchMetaCategories MimeJSON
-- | @text/json@
instance Produces SearchMetaCategories MimeTextjson
-- | @application/xml@
instance Produces SearchMetaCategories MimeXML
-- | @text/xml@
instance Produces SearchMetaCategories MimeTextxml


-- *** searchMetaSearchProviders

-- | @GET \/Search\/Meta\/SearchProviders@
-- 
-- Gets the available searchProvider names.
-- 
searchMetaSearchProviders 
  :: Accept accept -- ^ request accept ('MimeType')
  -> TransportForLondonUnifiedRequest SearchMetaSearchProviders MimeNoContent [Text] accept
searchMetaSearchProviders  _ =
  _mkRequest "GET" ["/Search/Meta/SearchProviders"]

data SearchMetaSearchProviders  
-- | @application/json@
instance Produces SearchMetaSearchProviders MimeJSON
-- | @text/json@
instance Produces SearchMetaSearchProviders MimeTextjson
-- | @application/xml@
instance Produces SearchMetaSearchProviders MimeXML
-- | @text/xml@
instance Produces SearchMetaSearchProviders MimeTextxml


-- *** searchMetaSorts

-- | @GET \/Search\/Meta\/Sorts@
-- 
-- Gets the available sorting options.
-- 
searchMetaSorts 
  :: Accept accept -- ^ request accept ('MimeType')
  -> TransportForLondonUnifiedRequest SearchMetaSorts MimeNoContent [Text] accept
searchMetaSorts  _ =
  _mkRequest "GET" ["/Search/Meta/Sorts"]

data SearchMetaSorts  
-- | @application/json@
instance Produces SearchMetaSorts MimeJSON
-- | @text/json@
instance Produces SearchMetaSorts MimeTextjson
-- | @application/xml@
instance Produces SearchMetaSorts MimeXML
-- | @text/xml@
instance Produces SearchMetaSorts MimeTextxml

